### ISSUE TITLE
RingBufferWheel 有内存溢出隐患

### ISSUE THREAD

**Issue by daoshenzzg** [crossoverJie/cim#98]
**Bug 描述**
RingBufferWheel 的 task 保存在 taskMap(HashMap) 中，而 remove(key)、cancel(id) 并没有对 taskMap 中进行 remove 操作。

**复现**
复现步骤:
```java
private static class ByteTask extends RingBufferWheel.Task {

        private byte[] b;

        public ByteTask(int size) {
            this.b = new byte[size];
        }

        @Override
        public void run() {
        }
    }
```
```java
    private static void test1() throws InterruptedException {
        ExecutorService executorService = Executors.newFixedThreadPool(2);
        RingBufferWheel wheel = new RingBufferWheel(executorService);
        while (true) {
            logger.info("task size={}, task map size={}", wheel.taskSize(), wheel.taskMapSize());
            TimeUnit.SECONDS.sleep(1);

            for (int i = 0; i < 1000; i++) {
                RingBufferWheel.Task task = new ByteTask(1024 * 1024);
                task.setKey(1);
                wheel.addTask(task);
            }
        }
    }
```
**预期结果**

**截图**
```
12:38:26.557 [main] INFO RingBufferWheelTest - task size=0, task map size=0
12:38:27.575 [main] INFO RingBufferWheel - delay task is starting
12:38:30.872 [main] INFO RingBufferWheelTest - task size=323, task map size=1000
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at RingBufferWheelTest$ByteTask.<init>(RingBufferWheelTest.java:64)
	at RingBufferWheelTest.test1(RingBufferWheelTest.java:26)
	at RingBufferWheelTest.main(RingBufferWheelTest.java:14)
```

**附加信息**

**Comment by crossoverJie** [comment]
已经修复，参考：
https://github.com/crossoverJie/cim/blob/fdea811903e77a93bbdac2a292e71b44de632dd2/cim-common/src/test/java/com/crossoverjie/cim/common/data/construct/RingBufferWheelTest.java#L29-L43
